### ISSUE TITLE
Animal Kingdom not listed in "embedded_nations"

### ISSUE THREAD

**Issue by cazfi** [dftec-es/civ2civ3_earth#1]
Near the top of nations.ruleset:

 ---

; List of nations to embed to main nations.ruleset despite separate nationlist
; being used for other nations.
embedded_nations = "barbarian", "pirate"

 ---

... and the bottom ...

 ---

; Please keep [ruledit] section in sync with these includes
*include "default/nationlist.ruleset"
; This ruleset uses model of 3 separate barbarian nations
*include "nation/barbarian.ruleset"
*include "nation/pirate.ruleset"
*include "nation/animals.ruleset"

 ---

This causes ruleup (and presumably also ruledit even within the same freeciv version) to save nations.ruleset without Animal Kingdom in it, resulting in ruleset load failure:

1: Invalid requirement Nation | Player |  |  | Animal Kingdom: bad type or name
1: "/work/freeciv/rulesets/3rd/S3_1/data/civ2civ3_earth/game.ruleset" [actionenabler_45] has invalid or unknown req: "Nation" "Animal Kingdom".

**Comment by dftec-es** [comment]
Thank you for reporting it here. I notice now that you pointed it in a osdn ticket, but at the time I thought you were talking about a change needed in ruledit, I didn't realize the change was needed in the ruleset itself.

I'll fix it for next version.

**Comment by dftec-es** [comment]
Fixed in f6e15b79c0007a1990982c03ec53a574cedaaf0e
